apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-docker-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sonar-docker-k8s
  template:
    metadata:
      labels:
        app: sonar-docker-k8s
    spec:
      containers:
      - name: sonar-docker-k8s
        image: shankarduppala/sonar-docker-k8s:dev-21
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
